name = "email-to-telegram"
main = "src/index.js"
compatibility_date = "2025-09-21"
[ vars ]
TOKEN = "8209677108:AAHflFtRLfc3hKCq-mg81GwD714yRwh7wtE"
send_email = [
    {type = "send_email", name = "SEB"},
]
CFURL = "https://email-to-telegram.maronponst.workers.dev/"

[[ d1_databases ]]
binding = "DB"
database_name = "emaildb"
database_id = "aecf3bf9-ad28-4338-a7d7-66ecd57de976"
